trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '77f3b92a-0a3b-489f-be5f-77329ce7e7f4'
  imageRepository: 'devopspythonapp'
  containerRegistry: 'mycontainerregistry10.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  azureSubscription: 'azureSubscription'
  containerGroupName: 'devopspythonapp'
  containerName: 'devopspythonapp'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Test
  displayName: Test stage
  jobs:
  - job: Test
    displayName: Run unit tests
    pool:
      vmImage: $(vmImageName)
      parallel: 1
    steps:
    - script: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pytest test_add_numbers.py
      displayName: Run tests with Pytest
      
  - job: coverage
    displayName: Code coverage
    dependsOn: test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        coverage run --source=. -m pytest test_add_numbers.py
        coverage report -m
        coverage xml
      displayName: Run tests with Pytest and Coverage.py
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'cobertura'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/coverageReport'
      displayName: Publish code coverage results

- stage: Test Environment
  displayName: Test environment stage
  jobs:
  - job: TestEnvironment
    displayName: Deploy to test environment
    pool:
      vmImage: $(vmImageName)
      parallel: 1
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)-test
          
    - task: AzureCLI@2
      displayName: 'Create container group'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az container create \
            --resource-group myResourceGroup \
            --name $(containerGroupName)-test \
            --image $(containerRegistry)/$(imageRepository):$(tag)-test \
            --cpu 1 \
            --memory 1 \
            --ports 5000 \
            --ip-address public \
            --registry-login-server $(containerRegistry) \
            --registry-username 'mycontainerRegistry10' \
            --registry-password 'XukI3SdpRC3jxJzBtrt1tnD0IxN2p4lAMcuQv7mGp9+ACRAjE9Dt' \
            --dns-name-label $(containerName)-test

- stage: Production Approval
  displayName: Production Approval stage
  jobs:
  - job: ProductionApproval
    displayName: Approve production deployment
    pool:
      vmImage: $(vmImageName)
      parallel: 1
    steps:
    - task: PowerShell@2
      displayName: 'Prompt for approval'
      inputs:
        targetType: 'inline'
        script: |
          $title = "Production Deployment Approval"
          $message = "Do you approve the deployment to the production environment?"
          $yes = New-Object System.Management.Automation.Host.ChoiceDescription "&Yes", "Approve the deployment"
          $no = New-Object System.Management.Automation.Host.ChoiceDescription "&No", "Reject the deployment"
          $options = [System.Management.Automation.Host.ChoiceDescription[]]($yes, $no)
          $result = $host.ui.PromptForChoice($title, $message, $options, 0)
          if ($result -eq 0) {
            Write-Host "Deployment approved."
            exit 0
          } else {
            Write-Host "Deployment rejected."
            exit 1
          }

- stage: Production
  displayName: Production stage
  dependsOn: Production Approval
  jobs:
  - job: Production
    displayName: Deploy to production
    pool:
      vmImage: $(vmImageName)
      parallel: 1
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)-prod
          
    - task: AzureCLI@2
      displayName: 'Create container group'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az container create \
            --resource-group myResourceGroup \
            --name $(containerGroupName)-prod \
            --image $(containerRegistry)/$(imageRepository):$(tag)-prod \
            --cpu 1 \
            --memory 1 \
            --ports 5000 \
            --ip-address public \
            --registry-login-server $(containerRegistry) \
            --registry-username 'mycontainerRegistry10' \
            --registry-password 'XukI3SdpRC3jxJzBtrt1tnD0IxN2p4lAMcuQv7mGp9+ACRAjE9Dt' \
            --dns-name-label $(containerName)-prod